// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var PersonalInformation$ReactTemplate = require("./PersonalInformation.bs.js");

var component = ReasonReact.statelessComponent("Page");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, PersonalInformation$ReactTemplate.make("Khoa Nguyen", /* Some */[24], /* array */[]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
