// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var PersonalInformation = require("./PersonalInformation");

function make(name, age, children) {
  var tmp = {
    name: name
  };
  if (age) {
    tmp.age = age[0];
  }
  return ReasonReact.wrapJsForReason(PersonalInformation.default, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
