// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PersonalInformationJs = require("./PersonalInformation.js");

function make(name, age, showAge, children) {
  var tmp = {
    name: name
  };
  if (age) {
    tmp.age = age[0];
  }
  var tmp$1 = Js_option.map(Js_boolean.to_js_boolean, showAge);
  if (tmp$1) {
    tmp.showAge = tmp$1[0];
  }
  return ReasonReact.wrapJsForReason(PersonalInformationJs, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
